### ISSUE TITLE
Correction on Graph 1-5 and 6

### ISSUE THREAD

**Issue by MaxwellJay256** [longlin10086/HITSZ-CircLab#1]
实验 1-5 和 1-6 的电阻 R 值不同，导致两组的谐振时电流 $I_0$ 并不相同，而且也不是表 1-4 求出的那个谐振电流。
这导致你在 [CircLab_01.ipynb](https://github.com/longlin10086/HITSZ-CircLab/blob/main/Lab01/CircLab_01.ipynb) 的“2 表 1-5 与 表 1-6 数据”中画出的图有误。两条曲线的峰值都应该是 1，如该图：
![1_56](https://github.com/longlin10086/HITSZ-CircLab/assets/107470012/1fc1618f-9fb1-448a-be69-0d34e6a12dc7)

需要修改的代码应该是这几行：
```python
for i in range(0, len(f_new)):
    I_ans_5.append(round(I_5[i]/I_0, 2))
    I_ans_6.append(round(I_6[i]/I_0, 2))
    f_ans.append(round(f_new[i]/f_0, 2))
```

**Comment by longlin10086** [comment]
这个地方确实出了问题，感谢提醒！
